# Generated by Django 5.2 on 2025-04-10 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Dummy Platform 1', 'Dummy Platform 1'), ('Dummy Platform 2', 'Dummy Platform 2'), ('Dummy Platform 3', 'Dummy Platform 3')], max_length=50)),
                ('card_name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('cashback', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
