# Generated by Django 5.2 on 2025-04-29 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_systems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='bank',
            field=models.CharField(choices=[('ipotekabank', 'ipotekabank'), ('uzum', 'uzum'), ('Anorbank', 'Anorbank'), ('TBC bank', 'TBC bank'), ('Kapitalbank', 'Kapitalbank')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='card_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='card_type',
            field=models.CharField(choices=[('Uzcard', 'Uzcard'), ('Humo', 'Humo'), ('Visa', 'Visa')], max_length=10),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('destination_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tx_dest', to='external_systems.paymentcard')),
                ('source_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tx_source', to='external_systems.paymentcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
