# Generated by Django 5.2 on 2025-04-29 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_systems', '0002_alter_paymentcard_bank_alter_paymentcard_card_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cashback_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='OnSiteTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cashback_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_systems.paymentcard')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_systems.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_systems.platform')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_systems.location')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='external_systems.platform')),
            ],
            options={
                'unique_together': {('platform', 'location')},
            },
        ),
    ]
